### ISSUE TITLE
mongoDB error

### ISSUE THREAD

**Issue by engenheiro** [matteodem/meteor-boilerplate#79]
Hello Matteo. I having some trouble to run the meteor boilerplate on Modulus.IO server. Without the the boilerplate, works well. Whats the solution? Thanks.

You have any other server sugestions to use Meteor?

The error:

/mnt/data/2/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: database names cannot contain the character ' '
    at validateDatabaseName (/mnt/data/2/node_modules/mongodb/lib/mongodb/db.js:233:59)
    at new Db (/mnt/data/2/node_modules/mongodb/lib/mongodb/db.js:95:3)
    at connectFunction (/mnt/data/2/node_modules/mongodb/lib/mongodb/mongo_client.js:243:29)
    at Function.MongoClient.connect (/mnt/data/2/node_modules/mongodb/lib/mongodb/mongo_client.js:313:5)
    at Function.Db.connect (/mnt/data/2/node_modules/mongodb/lib/mongodb/db.js:2035:23)
    at new MongoConnection (packages/mongo/mongo_driver.js:151:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:44:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
[2015-03-08T21:28:58.141Z] Application CRASH detected. Exit code 8.
[2015-03-08T21:28:58.180Z] Application restarted

**Comment by matteodem** [comment]
What is the name of your collection?

**Comment by engenheiro** [comment]
I dont know. I have only uploaded the boilerplate for test.

2015-03-09 6:20 GMT-03:00 Matteo De Micheli <notifications@github.com>:

> What is the name of your collection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matteodem/meteor-boilerplate/issues/79#issuecomment-77821404>
> .
>



-- 
Abraços!
11 95343-7141 - TIM
Rodrigo Gabriel Piris <http://www.facebook.com/rodrigogabrielp>
<http://TudoPara.Vc>

**Comment by matteodem** [comment]
Please ask modulus.io what this error could be, since the boilerplate is succesfully hosted on boilerplate.meteor.com

**Comment by engenheiro** [comment]
Thanks Matteo! I changed the server to Digital Ocean. Its a nice option and works very well.
