### ISSUE TITLE
Can't orion create decompress.decompress TypeError

### ISSUE THREAD

**Issue by sokki** [matteodem/meteor-boilerplate#80]
On Mac OS 10.10 / node 0.12.0:
```
user:Meteor user$ orion create boilerplate-test
Downloading../usr/local/lib/node_modules/orion-cli/node_modules/transfer-github/lib/index.js:74
			decompress.decompress(function(error) {
			           ^
TypeError: undefined is not a function
    at Stream.<anonymous> (/usr/local/lib/node_modules/orion-cli/node_modules/transfer-github/lib/index.js:74:15)
    at Stream.emit (events.js:104:17)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/orion-cli/node_modules/transfer-github/node_modules/transfer/lib/index.js:61:11)
    at WriteStream.emit (events.js:129:20)
    at evalmachine.<anonymous>:1718:14
    at /usr/local/lib/node_modules/orion-cli/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:102:5
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
```

**Comment by matteodem** [comment]
Seems like it has to do with the transfer-github package.

**Comment by matteodem** [comment]
Please provide reproduction steps, since it works locally with node version 0.12.0

**Comment by sokki** [comment]
Sorry, I just had dependency problems. 
Updated nopt, required by decrompress, and everything is fine now.
